catalogs:
  content:
    '@nuxt/content': ^3.8.0
    '@nuxtjs/seo': ^3.2.2
    '@shikijs/colorized-brackets': ^3.15.0
    '@shikijs/transformers': ^3.14.0
    abcjs: ^6.5.2
    remark-abcjs: ^0.1.6
    unist-util-visit: ^5.0.0
    plain-shiki: ^0.3.2
    rehype-katex: ^7.0.1
    remark-math: ^6.0.0
    remark-reading-time: ^2.0.2
    shiki: ^3.15.0
  framework:
    '@dxup/nuxt': ^0.2.1
    ci-info: ^4.3.1
    cross-env: ^10.1.0
    nuxt: ^4.2.1
    sass-embedded: ^1.93.3
    typescript: ^5.9.3
    tsup: ^8.5.0
    unplugin-yaml: ^3.0.7
    vue: ^3.5.24
    vue-router: ^4.6.3
  quality:
    '@antfu/eslint-config': ^5.4.1
    '@zinkawaii/stylelint-config': ^0.3.3
    cspell: ^9.2.2
    eslint: ^9.39.1
    stylelint: ^16.25.0
  ui:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/ph': ^1.2.2
    '@nuxt/icon': ^2.1.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
    vue-virtual-scroller: 2.0.0-beta.8
  util:
    '@clack/prompts': ^0.11.0
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    '@vueuse/router': 14.0.0
    date-fns: ^4.1.0
    date-fns-tz: ^3.2.0
    fast-xml-parser: ^5.3.1
    minisearch: ^7.2.0
    nanoid: ^5.1.6
    oxc-minify: ^0.96.0
    p-limit: ^7.1.1
    parse-domain: ^8.2.2
    radash: ^12.1.1
    rimraf: ^6.1.0
    strip-ansi: ^7.1.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - rolldown
  - sharp
  - unrs-resolver

overrides:
  sharp: 0.33.4

packages:
  - 'packages/*'

patchedDependencies:
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
  '@vue/shared': patches/@vue__shared.patch

shamefullyHoist: true
