name: Sync to GitLab
on:
  push:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          GITLAB_URL: https://gitlab.com/XiaoYuan151/blog-v3.git
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "${GITLAB_URL}"
          git push gitlab --prune --mirror
